on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '00 */12 * * *'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
         repository: 'packwiz/packwiz'
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: ~1.8.2
        args: --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto Release(For User who can not download from github actions)
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Development Build"
          files: dist/packwiz_windows_amd64_v1/packwiz.exe
