on:
  workflow_dispatch:
  schedule:
    # run every 2 days
    - cron: 30 21 */2 * *
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        repository: 'packwiz/packwiz'
        
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: ~1.8.2
        args: --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: dist/packwiz_windows_amd64_v1/packwiz.exe
